name: Python Script Workflow

on:
  push:
    branches:
      - master

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade
        pip install random
        pip install openai
        pip install mysql.connector


    - name: Run Python scripts
      run: |
        python3 insert.py
        python3 generated_data.py
      working-directory: scripts


